global:
  scrape_interval: 10s
  external_labels:
    monitor: "masstransit"

scrape_configs:
  - job_name: "masstransit"
    scheme: http
    static_configs:
      - targets:
          - "host.docker.internal:8085"
          - "host.docker.internal:8081"
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
